services:
  sgn-dash:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile.dash
    ports:
      - "3000:3000"
    depends_on:
      sgn-migrate:
        condition: service_completed_successfully
  sgn-socket:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile.socket
    ports:
      - "8000:8000"
    depends_on:
      sgn-migrate:
        condition: service_completed_successfully
  sgn-migrate:
    build:
      context: .
      dockerfile: ./Dockerfile.migrate
    env_file:
      - ./.env
    depends_on:
      sgn-database:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: '"deno task --cwd ./packages/database db:migrate"'
    # command: '"echo $DB_URL"'
  sgn-database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - sgn-data:/var/lib/postgresql/data # Persistent storage for the database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sgn-data:
