FROM oven/bun

RUN apt-get update

RUN apt-get install curl -y

WORKDIR /app-sgn_server

COPY . .

RUN bun install

WORKDIR /app-sgn_server/apps/sgn-socket

RUN bun run ./build.ts

EXPOSE 8000

CMD ["./start-server.sh"]
