FROM oven/bun

WORKDIR /app-dash

ENV NODE_ENV=production

LABEL org.opencontainers.image.source=https://git.uninetwork.net/ancients-of-resonite/stargate-network

COPY . .

RUN bun install

WORKDIR apps/sgn-dash

RUN bun --bun run build

EXPOSE 3000

CMD ["bun", "--bun", "run", "./src/server.ts"]
