FROM oven/bun

RUN apt-get update

RUN apt-get install curl -y

LABEL org.opencontainers.image.source=https://git.uninetwork.net/ancients-of-resonite/stargate-network

WORKDIR /app

COPY . .

RUN bun install

WORKDIR /app/apps/sgn-socket

RUN bun run ./build.ts

WORKDIR /app

EXPOSE 8000

CMD ["./start-server.sh"]
