FROM oven/bun

RUN apt-get update

RUN apt-get install curl -y

WORKDIR /app

COPY . .

RUN bun install

WORKDIR /app/apps/sgn-socket

RUN bun run ./build.ts

WORKDIR /app

EXPOSE 8000

CMD ["./start-server.sh"]
