FROM denoland/deno

WORKDIR /app-dash

COPY . .

RUN deno install

RUN deno install --config apps/sgn-dash/deno.json

RUN deno task --cwd apps/sgn-dash build

EXPOSE 3000

CMD ["deno", "run", "-A", "apps/sgn-dash/.output/server/index.mjs"]
