on:
  workflow_dispatch:

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Install Necessary Tools
        run: |
          apt update
          echo "Installing Sudo ------"
          apt -y install sudo
          echo "Installing Iptables ------"
          apt -y install iptables
          echo "Installing fuse-overlayfs ------"
          apt -y install fuse-overlayfs
          echo "Installing modprobe ------"
          apt -y install kmod
      - name: Set up Docker
        uses: https://git.uninetwork.net/docker/setup-docker-action@v5
      - name: Docker Login
        uses: docker/login-action@v4
        with:
          registry: git.uninetwork.net
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: git.uninetwork.net/ancients-of-resonite/sgn-server:latest
          file: Dockerfile.server
